---

version: '3.9'

services:
  db:
    hostname: db
    image: postgres:15.3-alpine
    container_name: nlp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nlp
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - "6379:6379"
