# Generated by Django 4.2.8 on 2024-11-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='GigaChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(blank=True, verbose_name='API key')),
                ('auth_headers', models.TextField(blank=True, verbose_name='Authorization Header')),
                ('req_headers_keyword', models.TextField(blank=True, verbose_name='Request Header keyword')),
                ('auth_url', models.TextField(blank=True, verbose_name='Authorization url')),
                ('text_embedding_url', models.TextField(blank=True, verbose_name='Text embedding url')),
                ('completion_url', models.TextField(blank=True, verbose_name='Completion url')),
                ('request_timeout', models.FloatField(blank=True, null=True, verbose_name='Request timeout')),
                ('queue_timeout', models.FloatField(blank=True, null=True, verbose_name='Queue timeout')),
                ('response_timeout', models.FloatField(blank=True, null=True, verbose_name='Response timeout')),
                ('simultaneous_generations', models.IntegerField(default=10, verbose_name='Simultaneous generations')),
                ('quota_per_hour', models.IntegerField(blank=True, null=True, verbose_name='Quota per hour')),
            ],
            options={
                'verbose_name': 'GigaChat url',
                'verbose_name_plural': 'GigaChat urls settings',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('user_text', models.TextField(blank=True, verbose_name='User prompt')),
                ('system_text', models.TextField(blank=True, verbose_name='System prompt')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
            },
        ),
        migrations.CreateModel(
            name='YGPTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(blank=True, verbose_name='API key')),
                ('folder_id', models.TextField(blank=True, verbose_name='Folder ID')),
                ('headers', models.TextField(blank=True, verbose_name='Headers')),
                (
                    'url_operation_result_prefix',
                    models.TextField(blank=True, verbose_name='URL operation result prefix'),
                ),
                ('text_embedding_url', models.TextField(blank=True, verbose_name='Text embedding url')),
                ('completion_sync_url', models.TextField(blank=True, verbose_name='Completion sync url')),
                ('completion_async_url', models.TextField(blank=True, verbose_name='Completion async url')),
                ('request_timeout', models.FloatField(default=10, verbose_name='Request timeout')),
                ('sync_queue_timeout', models.FloatField(default=10, verbose_name='Synchron queue timeout')),
                ('response_timeout_async', models.FloatField(default=20, verbose_name='Response timeout async')),
                ('simultaneous_generations', models.IntegerField(default=10, verbose_name='Simultaneous generations')),
                ('sync_quota_per_hour', models.IntegerField(default=100, verbose_name='Synchronous quota per hour')),
                ('async_quota_per_hour', models.IntegerField(default=5000, verbose_name='Asynchronous quota per hour')),
            ],
            options={
                'verbose_name': 'YGPT url',
                'verbose_name_plural': 'YGPT urls settings',
            },
        ),
    ]
