# Generated by Django 4.2.8 on 2024-09-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='NeoNodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo_node_id', models.PositiveIntegerField()),
                ('protocol_json', models.JSONField()),
                ('value', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Neo Node Data',
                'verbose_name_plural': 'Neo Nodes Data',
            },
        ),
        migrations.CreateModel(
            name='PatientMedcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medcard_uuid', models.UUIDField(verbose_name='Medcard ID')),
                ('patient_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Patient ID')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medcard information',
                'verbose_name_plural': 'Medcards information',
            },
        ),
        migrations.CreateModel(
            name='ProtocolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_uuid', models.UUIDField()),
                ('protocol_json', models.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Protocol Data',
                'verbose_name_plural': 'Protocols Data',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                (
                    'patient_medcard',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medaggregator.patientmedcard'),
                ),
                (
                    'protocol_data',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medaggregator.protocoldata'),
                ),
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocols',
            },
        ),
        migrations.CreateModel(
            name='NeoNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                (
                    'neo_node_data',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medaggregator.neonodedata'),
                ),
                (
                    'patient_medcard',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medaggregator.patientmedcard'),
                ),
            ],
            options={
                'verbose_name': 'Neo Node',
                'verbose_name_plural': 'Neo Nodes',
            },
        ),
    ]
