# Generated by Django 4.2.8 on 2024-12-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medaggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedcard',
            name='medcard_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Medcard ID'),
        ),
        migrations.AddField(
            model_name='patientmedcard',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed at'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_custom_id',
            field=models.CharField(
                blank=True,
                help_text='User-defined arbitrary string. Do not edit manually!',
                max_length=50,
                verbose_name='Protocol Custom ID',
            ),
        ),
        migrations.AddField(
            model_name='protocol',
            name='service_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Service ID'),
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='protocol_data',
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Protocol data'),
        ),
        migrations.AlterUniqueTogether(
            name='patientmedcard',
            unique_together={('user_id', 'medcard_id')},
        ),
        migrations.AddConstraint(
            model_name='protocol',
            constraint=models.UniqueConstraint(
                condition=models.Q(('protocol_custom_id', ''), _negated=True),
                fields=('patient_medcard', 'protocol_custom_id'),
                name='unique_medcard_protocol_custom_id',
            ),
        ),
        migrations.DeleteModel(
            name='ProtocolData',
        ),
        migrations.RemoveField(
            model_name='patientmedcard',
            name='medcard_uuid',
        ),
        migrations.RemoveField(
            model_name='patientmedcard',
            name='patient_id',
        ),
    ]
