# Generated by Django 4.2.8 on 2024-12-10 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medaggregator', '0002_patientmedcard_medcard_id_patientmedcard_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmedcard',
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Medcard information',
                'verbose_name_plural': 'Medcards information',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
                'indexes': [models.Index(fields=['name'], name='medaggregat_name_90f370_idx')],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                (
                    'diagnosis_type',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(None, '(Undefined)'), (0, 'Temporary'), (1, 'Chronic')],
                        null=True,
                        verbose_name='Diagnosis type',
                    ),
                ),
                ('is_sent_to_lk', models.BooleanField(default=False, verbose_name='Is sent to LK')),
                (
                    'is_general',
                    models.BooleanField(
                        default=True,
                        help_text='If set to true, Doctor specialties field is being ignored',
                        verbose_name='Visible to all doctors',
                    ),
                ),
                (
                    'doctor_specialties',
                    models.ManyToManyField(
                        blank=True,
                        related_name='diagnoses',
                        to='medaggregator.speciality',
                        verbose_name='Doctor specialties',
                    ),
                ),
                (
                    'patient_medcard',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='diagnoses',
                        to='medaggregator.patientmedcard',
                        verbose_name='Patient Medcard',
                    ),
                ),
                (
                    'protocols',
                    models.ManyToManyField(
                        blank=True, related_name='diagnoses', to='medaggregator.protocol', verbose_name='Protocols'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='PatientStringParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, max_length=50, verbose_name='Group ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                (
                    'diagnosis',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='string_params',
                        to='medaggregator.diagnosis',
                        verbose_name='Diagnosis',
                    ),
                ),
                (
                    'protocol',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='string_params',
                        to='medaggregator.protocol',
                        verbose_name='Protocol',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient string parameter',
                'verbose_name_plural': 'Patients string parameters',
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['date'], name='medaggregat_date_ad2d3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientDigitalParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50, verbose_name='Group ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Value')),
                ('date', models.DateField(verbose_name='Date')),
                (
                    'diagnosis',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='digital_params',
                        to='medaggregator.diagnosis',
                        verbose_name='Diagnosis',
                    ),
                ),
                (
                    'protocol',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='digital_params',
                        to='medaggregator.protocol',
                        verbose_name='Protocol',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Patient digital parameter',
                'verbose_name_plural': 'Patients digital parameters',
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['date'], name='medaggregat_date_47fa39_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['date_created'], name='medaggregat_date_cr_09e153_idx'),
        ),
    ]
