# Generated by Django 4.2.8 on 2024-12-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medaggregator', '0003_alter_patientmedcard_options_speciality_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdigitalparam',
            options={'verbose_name': 'Patient digital parameter', 'verbose_name_plural': 'Patients digital parameters'},
        ),
        migrations.AlterModelOptions(
            name='patientstringparam',
            options={'verbose_name': 'Patient string parameter', 'verbose_name_plural': 'Patients string parameters'},
        ),
        migrations.RemoveIndex(
            model_name='patientdigitalparam',
            name='medaggregat_date_47fa39_idx',
        ),
        migrations.RemoveIndex(
            model_name='patientstringparam',
            name='medaggregat_date_ad2d3c_idx',
        ),
        migrations.RemoveField(
            model_name='patientdigitalparam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patientstringparam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='processed_at',
        ),
        migrations.AddField(
            model_name='patientmedcard',
            name='reprocessed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reprocessed at'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='attentions_changed',
            field=models.BooleanField(default=False, verbose_name='Attention(s) changed'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Classified at'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='loaded_to_graphdb_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Loaded to Neo at'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='unmarked_features_left',
            field=models.BooleanField(default=False, verbose_name='Unmarked features left'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='patient_medcard',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='protocols',
                to='medaggregator.patientmedcard',
                verbose_name='Patient Medcard ID',
            ),
        ),
    ]
