# Generated by Django 4.2.8 on 2025-01-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medaggregator', '0004_alter_patientdigitalparam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='logging_from_marked',
            field=models.TextField(blank=True, verbose_name='Logging from marked'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='marked_with_errors',
            field=models.BooleanField(default=False, verbose_name='Marked with errors'),
        ),
        migrations.AddField(
            model_name='patientmedcard',
            name='additional_marked_with_errors',
            field=models.BooleanField(default=False, verbose_name='Additional marked with errors'),
        ),
        migrations.AddField(
            model_name='patientmedcard',
            name='logging_from_marked',
            field=models.TextField(blank=True, verbose_name='Logging from marked'),
        ),
    ]
