# Generated by Django 4.2.8 on 2025-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medaggregator', '0005_protocol_logging_from_marked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='is_medtest',
            field=models.BooleanField(default=False, verbose_name='This is medtest'),
        ),
    ]
