# Generated by Django 4.2.8 on 2025-02-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medaggregator', '0006_protocol_is_medtest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='protocol',
            name='unique_medcard_protocol_custom_id',
        ),
        migrations.AddConstraint(
            model_name='protocol',
            constraint=models.UniqueConstraint(
                condition=models.Q(('protocol_custom_id', ''), _negated=True),
                fields=('patient_medcard', 'protocol_custom_id', 'is_medtest'),
                name='unique_medcard_protocol_custom_id',
            ),
        ),
    ]
