# Generated by Django 4.2.8 on 2024-11-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FeatureClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(verbose_name='Features')),
                ('importance', models.TextField(blank=True, verbose_name='Importance')),
            ],
            options={
                'verbose_name': 'Feature Classifier',
                'verbose_name_plural': 'Features Classifier',
            },
        ),
    ]
