# Generated by Django 4.2.8 on 2024-11-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature_classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureclassifier',
            name='annoy_score',
            field=models.TextField(blank=True, verbose_name='Annoy scores'),
        ),
    ]
