# Generated by Django 4.2.8 on 2024-11-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature_classifier', '0002_featureclassifier_annoy_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureclassifier',
            name='gpt_description',
            field=models.TextField(blank=True, verbose_name='GPT description'),
        ),
    ]
