# Generated by Django 4.2.8 on 2024-11-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature_classifier', '0003_featureclassifier_gpt_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFeatureClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(verbose_name='Features')),
                ('additional_feature', models.TextField(verbose_name='Additional features')),
                ('importance', models.TextField(blank=True, verbose_name='Importance')),
                ('annoy_score', models.TextField(blank=True, verbose_name='Annoy scores')),
                ('gpt_description', models.TextField(blank=True, verbose_name='GPT description')),
            ],
            options={
                'verbose_name': 'Additional feature Classifier',
                'verbose_name_plural': 'Additional features Classifier',
            },
        ),
    ]
