# Generated by Django 4.2.8 on 2024-11-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature_classifier', '0004_additionalfeatureclassifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfeatureclassifier',
            name='additional_feature',
            field=models.TextField(blank=True, verbose_name='Additional features'),
        ),
    ]
