# Generated by Django 4.2.8 on 2024-11-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature_classifier', '0005_alter_additionalfeatureclassifier_additional_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Name')),
                ('value', models.TextField(verbose_name='Value')),
                ('gpt_description', models.TextField(verbose_name='GPT description')),
            ],
            options={
                'verbose_name': 'Feature description Classifier',
                'verbose_name_plural': 'Feature descriptions Classifier',
                'unique_together': {('name', 'value')},
            },
        ),
    ]
