# Generated by Django 4.2.8 on 2025-03-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feature_classifier', '0006_descriptionfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbbreviatedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviated_phrase', models.TextField(unique=True, verbose_name='Abbreviated phrase')),
                ('decrypted_phrase', models.TextField(verbose_name='Decrypted phrase')),
            ],
            options={
                'verbose_name': 'Abbreviated phrase',
                'verbose_name_plural': 'Abbreviated phrases',
            },
        ),
    ]
