# Generated by Django 4.2.1 on 2023-11-18 17:58

from django.db import migrations

import nlp.apps.common.models


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', nlp.apps.common.models.CustomUserManager()),
            ],
        ),
    ]
