# Generated by Django 4.2.1 on 2024-10-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'model',
                    models.CharField(
                        default='PrunaAI/IlyaGusev-saiga_llama3_8b-AWQ-4bit-smashed',
                        max_length=255,
                        verbose_name='Model',
                    ),
                ),
                ('temperature', models.FloatField(default=0.0, verbose_name='Temperature')),
                ('top_p', models.FloatField(default=0.99, verbose_name='Top P')),
                ('max_tokens', models.IntegerField(default=2000, verbose_name='Max Tokens')),
                ('repetition_penalty', models.FloatField(default=1.0, verbose_name='Repetition Penalty')),
                ('seed', models.IntegerField(default=0, verbose_name='Seed')),
            ],
            options={
                'verbose_name': 'LLM setting',
                'verbose_name_plural': 'LLM settings',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('user_text', models.TextField(blank=True, verbose_name='User prompt')),
                ('system_text', models.TextField(blank=True, verbose_name='System prompt')),
                ('example_request_text', models.TextField(blank=True, verbose_name='Example request prompt')),
                ('example_answer_text', models.TextField(blank=True, verbose_name='Example answer prompt')),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
            },
        ),
    ]
