# Generated by Django 4.2.1 on 2024-10-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('secret_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='user_text',
        ),
        migrations.AlterField(
            model_name='llmsettings',
            name='max_tokens',
            field=models.IntegerField(default=9000, verbose_name='Max Tokens'),
        ),
    ]
