# Generated by Django 4.2.1 on 2024-11-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('secret_settings', '0002_remove_prompt_user_text_alter_llmsettings_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmsettings',
            name='name',
            field=models.CharField(
                db_index=True, default='feature extraction', max_length=100, unique=True, verbose_name='Name'
            ),
        ),
        migrations.AlterField(
            model_name='llmsettings',
            name='max_tokens',
            field=models.IntegerField(default=3000, verbose_name='Max Tokens'),
        ),
    ]
