# Generated by Django 5.1.3 on 2024-11-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('secret_settings', '0003_llmsettings_name_alter_llmsettings_max_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsettings',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Model'),
        ),
    ]
