# Generated by Django 5.1.3 on 2024-12-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('secret_settings', '0004_alter_llmsettings_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        db_index=True, default='Descriptions', max_length=100, unique=True, verbose_name='Name'
                    ),
                ),
                ('structure', models.CharField(max_length=1024, verbose_name='Structure')),
            ],
            options={
                'verbose_name': 'DB setting',
                'verbose_name_plural': 'DB settings',
            },
        ),
        migrations.CreateModel(
            name='GlobalProcessingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text='Indicates whether this setup is currently active.',
                        verbose_name='Is Active',
                    ),
                ),
                ('shifted_window', models.BooleanField(default=True, verbose_name='Shifted Window')),
                ('unification', models.BooleanField(default=True, verbose_name='Unification')),
                ('rephrase', models.BooleanField(default=True, verbose_name='Rephrase')),
            ],
            options={
                'verbose_name': 'Global LLM Processing setting',
                'verbose_name_plural': 'Global LLM Processing settings',
            },
        ),
    ]
