# Generated by Django 5.1.3 on 2024-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('secret_settings', '0005_dbstructure_globalprocessingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstructure',
            name='structure',
            field=models.CharField(max_length=100024, verbose_name='Structure'),
        ),
    ]
