# Generated by Django 5.1.4 on 2024-12-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('secret_settings', '0006_alter_dbstructure_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='answer_format',
            field=models.TextField(blank=True, verbose_name='Answer format'),
        ),
    ]
