# Generated by Django 5.1.4 on 2024-12-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('secret_settings', '0007_prompt_answer_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstructure',
            name='structure',
            field=models.JSONField(verbose_name='Structure'),
        ),
    ]
