# Generated by Django 5.1.4 on 2025-01-13 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('secret_settings', '0008_alter_dbstructure_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Entity Name')),
                ('entity_class', models.CharField(max_length=100, verbose_name='Class')),
                (
                    'parents',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name='Parents',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
    ]
