# Generated by Django 5.1.4 on 2025-01-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('secret_settings', '0009_dbentities'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbentities',
            name='uploaded_to_pkl',
            field=models.BooleanField(default=False, verbose_name='Uploaded to pkl'),
        ),
    ]
