# Generated by Django 4.2.1 on 2024-03-12 15:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField()),
                (
                    'result',
                    models.ImageField(),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
            },
        ),
    ]
