# Generated by Django 4.2.1 on 2024-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('background_remover', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('filename', models.CharField(editable=False, max_length=50, verbose_name='Filename')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Requested at')),
                ('errors', models.TextField(blank=True, verbose_name='Errors')),
            ],
            options={
                'verbose_name': 'Image information',
                'verbose_name_plural': 'Images information',
            },
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
