# Generated by Django 4.2.1 on 2024-08-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medcard_id', models.CharField(blank=True, max_length=50, verbose_name='Medcard ID')),
                ('user_id', models.CharField(blank=True, max_length=50, verbose_name='User ID')),
                ('raw_text', models.TextField(verbose_name='Raw Text')),
                ('result', models.JSONField(max_length=50, verbose_name='Result')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocols',
            },
        ),
    ]
