# Generated by Django 4.2.1 on 2024-08-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('protocol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['-processed_at'], 'verbose_name': 'Protocol', 'verbose_name_plural': 'Protocols'},
        ),
        migrations.AddField(
            model_name='protocol',
            name='service_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Service ID'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='result',
            field=models.JSONField(blank=True, null=True, verbose_name='Result'),
        ),
    ]
