# Generated by Django 4.2.1 on 2024-11-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('protocol', '0002_alter_protocol_options_protocol_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='protocol_custom_id',
            field=models.CharField(
                blank=True,
                help_text='User-defined arbitrary string. Do not edit manually!',
                max_length=50,
                verbose_name='Protocol Custom ID',
            ),
        ),
    ]
