# Generated by Django 5.1.3 on 2024-11-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('protocol', '0003_protocol_protocol_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='api_error_count',
            field=models.IntegerField(default=0, verbose_name='API errors count'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='parsing_error_count',
            field=models.IntegerField(default=0, verbose_name='Parsing errors count'),
        ),
        migrations.CreateModel(
            name='ParsingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_text', models.TextField(blank=True, verbose_name='Error text')),
                ('llm_response', models.JSONField(blank=True, null=True, verbose_name='LLM response')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Processed at')),
                (
                    'protocol',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parsing_errors',
                        to='protocol.protocol',
                        verbose_name='Protocol',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Parsing error',
                'verbose_name_plural': 'Parsing errors',
                'ordering': ['-pk'],
            },
        ),
    ]
