# Generated by Django 5.1.3 on 2024-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('protocol', '0004_protocol_api_error_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingerror',
            name='error_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Error type'),
        ),
    ]
