# Generated by Django 5.1.3 on 2024-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('protocol', '0005_parsingerror_error_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsingerror',
            old_name='error_text',
            new_name='traceback',
        ),
        migrations.AddField(
            model_name='parsingerror',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error message'),
        ),
    ]
