# Generated by Django 5.1.3 on 2024-12-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('protocol', '0006_rename_error_text_parsingerror_traceback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingerror',
            name='traceback',
            field=models.TextField(blank=True, verbose_name='Traceback'),
        ),
    ]
