# Generated by Django 5.1.3 on 2024-12-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('protocol', '0007_alter_parsingerror_traceback'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='is_sent_to_graphdb',
            field=models.BooleanField(default=False, verbose_name='Is sent to GraphDB'),
        ),
    ]
