# Generated by Django 5.1.4 on 2024-12-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('protocol', '0008_protocol_is_sent_to_graphdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolStructureError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errors', models.JSONField(blank=True, null=True, verbose_name='Errors')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                (
                    'protocol',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='structure_errors',
                        to='protocol.protocol',
                        verbose_name='Protocol',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Protocol structure error',
                'verbose_name_plural': 'Protocol structure errors',
                'ordering': ['-pk'],
            },
        ),
    ]
