# Generated by Django 5.1.4 on 2024-12-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('protocol', '0009_protocolstructureerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='is_saved_to_graphdb',
            field=models.BooleanField(default=False, verbose_name='Is saved to GraphDB'),
        ),
    ]
